1. Explore the data

### The Colorado River Basin data is derived from both the analysis and extropolation of 9 public, recorded meetings of water control boards within the region, and a literature/article search of literature discussing water events within the geographical area that were published between 2005 - 2021. The percieved or intended value of the dataset centres around understanding the social vulnerability surrounding water scarcity, as well as the conflicts and crises around water resource management with the Colorado River Basin region. 

#### Holloman, D.V., Hines, M.K., and Zoanni, D.K., 2023, Coded Water Conflict and Crisis Events in the Colorado River Basin, Derived from LexisNexis search 2005-2021: U.S. Geological Survey data release, https://doi.org/10.5066/P9X6WR7J. Accessed: 7 October 2026

In [3]:
import pandas as pd
import numpy as np

df = pd.read_csv('data/Colorado River Basin Water Conflict Table.csv')

In [4]:
df.head()
df.tail()

,Event,Search Source,Newspaper,Article Title,Duplicate,Report Date,Report Year,Event Date,Event Day,Event Month,...,Article Text Search - water rights,Article Text Search - intergovernmental,Article Text Search - water transfers,Article Text Search - navigation,Article Text Search - fish,Article Text Search - invasive,Article Text Search - diversion,Article Text Search - water diversion,Article Text Search - instream,Article Text Search - aquatic
263,264,USGS301-350.docx,The Durango Herald (Colorado),Water officials consider action for worst case...,False,9-Jun-09,2019.0,6,NaN,6.0,...,3,0,0,0,0,0,0,0,0,0
264,265,USGS301-350.docx,"Rio Blanco Herald Times (Meeker, Colorado)",Rangely hosts Colorado River District event,False,21-Apr-22,2022.0,4/13/2022,13.0,4.0,...,3,0,0,0,0,1,1,0,0,0
265,266,USGS301-350.docx,Casa Grande Dispatch (AZ),California water district lawsuit threatens dr...,False,18-Apr-19,2019.0,4,NaN,4.0,...,2,0,0,0,0,0,0,0,0,0
266,267,USGS301-350.docx,The Salt Lake Tribune,Scientists want to flush water past Glen Canyo...,False,13-Dec-07,2007.0,12,NaN,12.0,...,0,0,0,0,0,2,0,0,0,0
267,268,USGS301-350.docx,Casa Grande Dispatch (AZ),Arizona plan could devastate Pinal farmers,NaN,2-Feb-19,2019.0,1/31/2019,31.0,1.0,...,2,0,0,0,0,0,0,0,0,0

In [6]:
df.shape

(268, 48)

In [7]:
df.describe()

,Event,Report Year,Event Day,Event Month,Event Year,County FIPS,Intensity Value,Article Text Search - water quality,Article Text Search - invasive species,Article Text Search - conservation,...,Article Text Search - water rights,Article Text Search - intergovernmental,Article Text Search - water transfers,Article Text Search - navigation,Article Text Search - fish,Article Text Search - invasive,Article Text Search - diversion,Article Text Search - water diversion,Article Text Search - instream,Article Text Search - aquatic
count,268.000000,265.000000,18.000000,212.000000,257.000000,8.000000,255.000000,268.000000,268.000000,268.000000,...,268.000000,268.000000,268.000000,268.000000,268.000000,268.000000,268.000000,268.000000,268.000000,268.000000
mean,134.500000,2017.449057,18.444444,6.259434,2016.591440,11170.500000,0.219608,0.671642,0.014925,2.007463,...,3.134328,0.003731,0.022388,0.007463,0.410448,0.033582,0.182836,0.011194,0.089552,0.093284
std,77.509139,4.314160,6.887518,3.679539,10.346365,15437.657326,1.995765,1.472729,0.121481,2.633681,...,3.456072,0.061085,0.148219,0.086225,1.109798,0.200166,0.734493,0.105405,0.860822,0.632064
min,1.000000,2005.000000,4.000000,1.000000,1900.000000,4027.000000,-4.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,67.750000,2015.000000,13.250000,3.000000,2015.000000,4027.000000,-1.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,134.500000,2019.000000,19.000000,5.000000,2019.000000,6047.000000,0.000000,0.000000,0.000000,1.000000,...,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,201.250000,2021.000000,20.000000,9.000000,2021.000000,8067.000000,1.500000,1.000000,0.000000,3.000000,...,5.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,268.000000,2022.000000,31.000000,12.000000,2023.000000,49055.000000,5.000000,10.000000,1.000000,15.000000,...,18.000000,1.000000,1.000000,1.000000,8.000000,2.000000,7.000000,1.000000,12.000000,9.000000

In [8]:
df['Issue Type'].value_counts()

Issue Type
Drought                                                                       66
Water rights more generally                                                   51
Conservation                                                                  43
Intergovernmental issues                                                      43
Infrastructure issues                                                         15
Water quality                                                                 10
Water transfers                                                                6
Instream water rights                                                          6
Flood                                                                          4
Intergovernmental issues: Water rights more generally                          2
Intergovernmental issues: Drought                                              1
Intergovernmental issues: Water transfers                                      1
Intergovernmental issues: Conservation                                         1
Conservation; Drought                                                          1
Fish passage                                                                   1
Ground water depletion                                                         1
Conservation; Water rights more generally                                      1
Drought; Water quality; Water rights more generally; Infrastructure issues     1
Conservation; Ground water depletion                                           1
Name: count, dtype: int64

In [10]:
df['Place'].unique()

array(['Durango, CO', 'Great Salt Lake',
       'Colorado River Indian Reservation',
       'Southern Ute Indian Reservation', 'State of Arizona',
       'Entire Colorado River Basin', 'All of Colorado River Basin',
       'Farmington, OH; Great Salt Lake', 'Navajo Nation; Window Rock AZ',
       'Bullhead City, AZ re: All of Colorado R. Basin', 'Phoenix, AZ',
       'Ute Tribe, Utah', 'Denver, CO; Shoshone power plant',
       'AZ, CO, NM, UT, Southern Ute Tribe, Ute Mountain tribe, Navajo Nation',
       'Colorado River Basin', 'Laughlin, AZ',
       'Colorado River Indian Reservation; Parker, AZ',
       'CA - Imperial Irrigation District', 'Flagstaff, AZ',
       'Glen Canyon Dam, Lake Powell, UT; AZ', 'Needles, CA',
       'AZ, NV, Mexico', 'CO, UT, WY, NM', 'Las Vegas, Southern CA; AZ',
       'Sacaton/Gila R. Indian Reservation', 'Boulder, CO', 'Lees Ferry',
       'AZ', 'Lake Powell (UT, AZ)', 'Glenwod Springs',
       'Multiple waterways in UT ', 'St. Michaels, AZ',
       'The Front Range, CO/WY', 'CO', 'Flagstaff, AZ; UT',
       'Las Vegas, Flagstaff, AZ', 'CO (also Phoenix/Tucson, AZ',
       'Window Rock, AZ; Navajo Nation', 'Upper basin states',
       'Greeley, CO', 'AZ, CA, CO, NV, NM, UT, WY',
       'Scottsdale, Tucson, Phoenix, AZ', 'AZ, CA, NV', 'AZ; CA',
       'Las Vegas, NV', 'Hermosa Creek',
       'Phoenix, AZ/AZ; CA; CO, NV; NM; UT, WY', 'Animas River',
       'Lake Mead', 'Long Hollow Dam', 'White River', 'Glendale',
       'Colorado River', 'Southwestern US', 'Garfield County, CO',
       'San Juan River', 'Colorado River System',
       'Navajo Nation, Hopi Reservation', 'Gila River Indian Reservation',
       'Navajo Nation', 'Green River', 'Routt County, CO',
       'Pinal County, AZ', 'Pecos River', 'Colorado State',
       'Navajo/Hopi Reservations, Lower Colorado River', 'Flaming Gorge',
       'Lake Powell', 'Lake Powell, Lake Mead, Gila River',
       'Salt Lake City', 'State of Colorado', 'Pheonix, AZ',
       'Boulder City, NV', 'Salton Sea', 'Mancos River Watershed',
       'California State', 'Washington D.C.', 'Navajo/Hopi Nations',
       'Animas River including Junction and Lightner Creeks from Bakers Bridge to the New Mexico line, La Plata RIver from Mayday to the New Mexico State line, Vellecito Creek, Pine River from Vallecito to the Southern Ute Indian Tribe reservation south of Bayfield, Florida River,',
       'The application for Utah water rights requests 55,000 acre feet of water from the Green River with two pump stations located five miles from the Colorado state line in Dagget County, Utah, on Bureau of Land Management land. The water would then run through a hydroelectric facility before being piped nearly 500 miles northeast into Wyoming and then south down the Colorado Front Range',
       nan, 'Denver, CO', 'Yuma, AZ', 'Yampa Valley, CO', 'Tuscon, AZ',
       'Central Arizona Project, AZ',
       'San Juan County, San Juan River, Navajo Nation',
       'Hoover Dam, Clark County, NV', 'Green River Community, Utah',
       'San Juan River and Lake Powell', 'Navajo Nation, AZ',
       'White Mountain Apache lands Northeast/central AZ, CRIT lands along western edge of AZ and into CA',
       'South of the Seedskadee National Wildlife Refuge',
       'State of California, Nevada, Arizona', 'Glen Canyon Dam',
       'Yuma County, AZ', 'New Mexico, Arizona',
       'Wyoming, Utah, Colorado', 'Glen Canyon Dam, Grand Canyon',
       'Animas River near Silverton, San Juan River to Lake Powell',
       'Meeker, Colorado', 'Arizona ',
       'Arizona, California, Colorado, Nevada, New Mexico, Utah, Wyoming',
       'Lower Basin', 'Navajo Generating Station, near Page, AZ',
       'La Plata County, Animas River Valley', 'Cibola, AZ',
       'Lake Mead; Bullhead City, AZ', 'Colorado River Delta',
       'Little Colorado River Basin', 'State of Utah',
       'San Juan River; Navajo Nation; New Mexico',
       'Colorado; Phoenix AZ', 'Arizona',
       'Wayne County, Utah; Green River',
       'Lower Arkansas Valley Water Conservancy District',
       'Upper Colorado River Basin', 'Green River; Utah',
       'Lower Colorado River Basin', 'Salton Sea; California',
       'Arizona; entire Colorado River Basin',
       'Rio Blanco Water Conservancy District; State of Colorado',
       'Navajo and Hopi Nations/Little Colorado River', 'Bear River',
       'Utah', 'Scottsdale, AZ', 'Colorado ', 'Grand Valley, CO',
       'Austin, TX', 'Western Slope, CO', 'Salt River', 'Green River, UT',
       'Tempe, AZ', 'Yuma, AZ ', 'Glen Canyon Dam, AZ',
       'State of Arizona, State of California'], dtype=object)

In [11]:
df['State'].value_counts()

State
AZ                            66
CO                            34
UT                            27
NV                            10
CA                             7
NM                             6
AZ; CA                         4
AZ; UT                         3
AZ; CA; CO; NV; NM; UT; WY     3
AZ; NV                         2
NV; AZ                         2
CO; AZ                         2
CO; UT; WY; NM                 2
AZ; NM                         1
CA; NV; AZ                     1
WY; UT; CO                     1
UT; CO; WY                     1
CO; WY                         1
AZ; CA; NV                     1
UT; AZ                         1
AZ; CO; NM; UT                 1
OH; UT                         1
TX                             1
Name: count, dtype: int64

In [13]:
df['Conflict Present'].value_counts()

Conflict Present
Y    145
N    107
Name: count, dtype: int64

In [16]:
df['State'].unique()

array(['CO', 'UT', nan, 'AZ', 'OH; UT', 'AZ; CO; NM; UT', 'CA', 'AZ; UT',
       'AZ; NV', 'CO; UT; WY; NM', 'AZ; CA', 'UT; AZ', 'CO; WY', 'NV; AZ',
       'CO; AZ', 'AZ; CA; CO; NV; NM; UT; WY', 'AZ; CA; NV', 'NV', 'NM',
       'UT; CO; WY', 'CA; NV; AZ', 'AZ; NM', 'WY; UT; CO', 'TX'],
      dtype=object)

In [17]:

import numpy as np
import pandas as pd 

# Example series
s = pd.Series(['California; Nevada', 'Arizona', np.nan, 'Nevada; Utah'])
s

0    California; Nevada
1               Arizona
2                   NaN
3          Nevada; Utah
dtype: object

In [21]:
# CELL 2
# str accessor (doesn't do anything by itself)
s.str

# CELL 3
# Use str accessor with additional methods to perform string operations
s.str.split(';')

# CELL 4
s.str.split(';').explode()

0    California
0        Nevada
1       Arizona
2           NaN
3        Nevada
3          Utah
dtype: object

In [22]:
df.notna()

,Event,Search Source,Newspaper,Article Title,Duplicate,Report Date,Report Year,Event Date,Event Day,Event Month,...,Article Text Search - water rights,Article Text Search - intergovernmental,Article Text Search - water transfers,Article Text Search - navigation,Article Text Search - fish,Article Text Search - invasive,Article Text Search - diversion,Article Text Search - water diversion,Article Text Search - instream,Article Text Search - aquatic
0,True,True,True,True,True,True,True,False,False,True,...,True,True,True,True,True,True,True,True,True,True
1,True,True,True,True,True,True,True,False,False,True,...,True,True,True,True,True,True,True,True,True,True
2,True,True,True,True,True,True,True,False,False,True,...,True,True,True,True,True,True,True,True,True,True
3,True,True,True,True,True,True,True,False,False,True,...,True,True,True,True,True,True,True,True,True,True
4,True,True,True,True,True,True,True,False,False,True,...,True,True,True,True,True,True,True,True,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263,True,True,True,True,True,True,True,True,False,True,...,True,True,True,True,True,True,True,True,True,True
264,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
265,True,True,True,True,True,True,True,True,False,True,...,True,True,True,True,True,True,True,True,True,True
266,True,True,True,True,True,True,True,True,False,True,...,True,True,True,True,True,True,True,True,True,True
267,True,True,True,True,False,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True

In [24]:
df['State'].notna()

0       True
1       True
2       True
3      False
4      False
       ...
263     True
264     True
265     True
266     True
267     True
Name: State, Length: 268, dtype: bool

In [29]:
df.loc[df['State'].notna(), "State"]

0          CO
1          CO
2          UT
5          AZ
11     OH; UT
        ...
263        CO
264        CO
265    AZ; CA
266        AZ
267        AZ
Name: State, Length: 178, dtype: object

In [38]:
df.loc[df['State'].notna(), "State"]

0          CO
1          CO
2          UT
5          AZ
11     OH; UT
        ...
263        CO
264        CO
265    AZ; CA
266        AZ
267        AZ
Name: State, Length: 178, dtype: object

In [37]:
df[df['Conflict Present'] == 'Y']

,Event,Search Source,Newspaper,Article Title,Duplicate,Report Date,Report Year,Event Date,Event Day,Event Month,...,Article Text Search - water rights,Article Text Search - intergovernmental,Article Text Search - water transfers,Article Text Search - navigation,Article Text Search - fish,Article Text Search - invasive,Article Text Search - diversion,Article Text Search - water diversion,Article Text Search - instream,Article Text Search - aquatic
0,1,USGS1-50.docx,The Durango Herald (Colorado),Tribes assert water rights on Colorado River B...,False,7-Apr-22,2022.0,NaN,NaN,4.0,...,17,0,0,0,0,0,0,0,0,0
1,2,USGS1-50.docx,"Journal, The (Cortez, Dolores, Mancos, CO)",Native American tribes assert water rights on ...,False,7-Apr-22,2022.0,NaN,NaN,4.0,...,17,0,0,0,0,0,0,0,0,0
4,5,USGS1-50.docx,The Aspen Times (Colorado),Historically excluded from Colorado River poli...,False,19-Dec-21,2021.0,NaN,NaN,11.0,...,18,0,0,0,0,0,0,0,0,0
5,6,USGS1-50.docx,The Arizona Republic (Phoenix),Everyone loses if we cannot agree on how we us...,False,22-Apr-17,2017.0,NaN,NaN,4.0,...,1,0,0,0,0,0,0,0,0,0
7,8,USGS1-50.docx,"Navajo Times (Window Rock, Arizona)","Colorado River, stolen by law; Indigenous nati...",False,17-Mar-22,2022.0,NaN,NaN,3.0,...,15,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
257,258,USGS301-350.docx,The Arizona Republic (Phoenix),"At Canyon, water battle rages anew",False,22-Feb-09,2009.0,1,NaN,1.0,...,2,0,0,0,4,0,0,0,0,0
258,259,USGS301-350.docx,The Salt Lake Tribune,Alder: A new set of negotiations need for The ...,False,29-Aug-08,2008.0,8,NaN,8.0,...,4,0,0,0,2,0,0,0,2,0
260,261,USGS301-350.docx,Farmington Daily Times (New Mexico),Experts predict low San Juan County river flow...,False,11-Apr-15,2015.0,4,NaN,4.0,...,7,0,0,0,0,0,0,0,0,0
262,263,USGS301-350.docx,Associated Press State & Local,Officials: Arizona will miss US deadline for k...,False,20-Feb-19,2019.0,2/19/2019,19.0,2.0,...,6,0,0,0,0,0,0,0,0,0
265,266,USGS301-350.docx,Casa Grande Dispatch (AZ),California water district lawsuit threatens dr...,False,18-Apr-19,2019.0,4,NaN,4.0,...,2,0,0,0,0,0,0,0,0,0

In [41]:
df.loc[df['Conflict Present'] == 'Y', 'State'].str.split().explode().unique()

array(['CO', nan, 'AZ', 'OH;', 'UT', 'CA', 'AZ;', 'NV', 'CO;', 'UT;',
       'WY;', 'NM', 'NV;', 'CA;', 'NM;', 'WY'], dtype=object)

In [44]:
states_conflict = df.loc[df['Conflict Present'] == 'Y', 'State']
states_conflict

0          CO
1          CO
4         NaN
5          AZ
7         NaN
        ...
257        AZ
258        UT
260       NaN
262        AZ
265    AZ; CA
Name: State, Length: 145, dtype: object

In [45]:
states_split = states_conflict.str.split(";")
states_split

0           [CO]
1           [CO]
4            NaN
5           [AZ]
7            NaN
         ...
257         [AZ]
258         [UT]
260          NaN
262         [AZ]
265    [AZ,  CA]
Name: State, Length: 145, dtype: object

In [48]:
states_explode = states_split.explode()
states_explode

0       CO
1       CO
4      NaN
5       AZ
7      NaN
      ...
258     UT
260    NaN
262     AZ
265     AZ
265     CA
Name: State, Length: 179, dtype: object

In [50]:
states_unique = states_explode.unique()
states_unique

array(['CO', nan, 'AZ', 'OH', ' UT', 'UT', 'CA', ' NV', ' WY', ' NM',
       ' CA', 'NV', ' AZ', ' CO', 'NM', 'WY'], dtype=object)